---
- name: Download .rpm mysql repo  
  command: wget -P /tmp https://dev.mysql.com/get/mysql84-community-release-el8-1.noarch.rpm
#  get_url:
#    url: https://dev.mysql.com/get/mysql84-community-release-el8-1.noarch.rpm
#    dest: /tmp/mysql84-community-release-el8-1.noarch.rpm


- name: Install MySQL repo  
  ansible.builtin.dnf:  
    name: /tmp/mysql84-community-release-el8-1.noarch.rpm
    state: present

- name: Disable mysql-8.4-lts-community repo
  #command: dnf config-manager --disable mysql-tools-8.4-lts-community
  community.general.ini_file:
    path: /etc/yum.repos.d/mysql-community.repo
    section: mysql-8.4-lts-community
    option: enabled
    value: 0

- name: Enable mysql80-community repo
  #command: dnf config-manager --enable mysql80-community
  community.general.ini_file:
    path: /etc/yum.repos.d/mysql-community.repo
    section: mysql80-community
    option: enabled
    value: 1

- name: Disable default redhat mysql module
  command: dnf module disable mysql

- name: Install MySQL server  
  ansible.builtin.yum:  
    name: mysql-community-server
    state: present  

- name: Start MySQL service  
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Get the initial MySQL root password  
  command: grep 'temporary password' /var/log/mysqld.log  
  register: mysql_temp_password  
  changed_when: false

- name: Print MySQL temporary password  
  debug:  
    msg: "Temporary MySQL root password: {{ mysql_temp_password.stdout.split(' ')[-1] }}"